apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-app-config
  namespace: temporal-banking-app
data:
  BANKING_RELOAD: "0"
  BANKING_BACKEND_URL: http://backend:8000
  TEMPORAL_ADDRESS: demo-banking-app.a2dd6.tmprl.cloud:7233
  TEMPORAL_NAMESPACE: demo-banking-app.a2dd6
  TEMPORAL_TASK_QUEUE: MoneyTransfer
